---
title: <center>Android Applications</center>
output: html_document
---

<style type="text/css">

body{ /* Normal  */
      font-size: 18px;
  }
td {  /* Table  */
  font-size: 18px;
}
h1.title {
  font-size: 35px;
  color: Blue;
}
h1 { /* Header 1 */
  font-size: 28px;
  color: DarkBlue;
}

h2 { /* Header 2 represented by ## precursor*/
  font-size: 28px;
  color: DarkBlue;
  text-align: center
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## This page showcses the applications I have made for academic and learning purposes


1. Martial Arts Grading Application 

This application is a multi screen application to store grading scores
for Martial Arts, using a single level belt as an example.
The application uses functionality of Android Programming including
SQL, Data Storage on the App, Data Manipulation Functionality, Intents,
moving .gif displays and Password Entry

[Video Presentation](https://www.researchgate.net/publication/344704630_Martial_Arts_-_Java_Android_Application)

2. Habit Breaker Application

This application is a 30 day course of keeping track in a graphical display
from a drop down list of selected bad habits, in order to change a habit 
over the course of that period

[Video Presentation](https://twitter.com/mark_bozinovic/status/1275605239333183488)


<!-- #https://stackoverflow.com/questions/43840742/how-to-embed-local-video-in-r-markdown -->

[GitHub Link](https://github.com/MarkBozinovic/NIT6120_Assignment1)
