---
title: "Personal"
output: html_document
---

<style type="text/css">

body{ /* Normal  */
      font-size: 18px;
  }
td {  /* Table  */
  font-size: 18px;
}
h1.title {
  font-size: 35px;
  color: Blue;
}
h1 { /* Header 1 */
  font-size: 28px;
  color: DarkBlue;
}

</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Interests
1. Under the tutelage of Dr. John Jory, a 6th Dan Hapkido Martial Artist, 
since 2002, I have trained with John. John has in Association with
Korean Hapkido Federation [HKF Link] (http://www.koreanhapkidofederation.com/)
and Taekwondo and Hapkido Grand Master Sung Soo Lee [GM Link] (https://7tigers-jidokwan.com/html/grand-master-sung-soo-lee.html)
formed a hybrid Martial Art called Rolling Thunder.With his vast Martial Arts Experince, in depth knowledge of human anatomy and bio-mechanics and out of the box thinking, John has formualted Rolling Thunder Martial Arts. [RTMA Link] (https://twitter.com/search?q=%23rollingthundermartialarts&src=typed_query).
I currently hold a Hapkido Moohakwan Cho Dan Bo (Brown Belt Level)

2. In Education and advancement of knowledge,
I have continually commited to my education, recently completing my Masters degree
in Enterprise Resource Planning Systems. I also hold a Post Graduate Diploma in 
Software Development (RMIT Melbourne) and an Applied Science Undergraduate Degree
(Applied Chemistry)

3. I have travelled throughout Australia over many years now and vistied many
countries as well. Countries travelled to: Vietnam, Singapore, Hong Kong, England, Italy, Belgium, Czech Republic, All Former Yugoslav Republics, Germany, Netherlands and France.

4. Sport
I enjoy Australian domestic sports including Cricket and Australian Rules Football.
I played cricket at club level for 12 years as an opening batter and love
attending games of Australia Rules Football and Cricket at the Melbourne Cricket Ground
being a Melbourne Cricket Club Member
[MCC Link] (https://www.mcc.org.au/)


