---
title: "Professional Portfolio"
output: html_document
---

<style type="text/css">

<<<<<<< HEAD
body {
    background-color: #4FB6C0;
  }

=======
>>>>>>> ef7ecdbdf26853cb5ecde0fb156353e790ebcf94
body{ /* Normal  */
      font-size: 18px;
  }
td {  /* Table  */
  font-size: 18px;
}
h1.title {
  font-size: 35px;
  color: Blue;
}
h1 { /* Header 1 */
  font-size: 28px;
  color: DarkBlue;
}

</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Transdev - Jun 2017 to current

I am currently employed with Transdev Melbourne [TD Link](https://www.transdevmelbourne.com.au/) as a Service Delivery Specialist. 

This role includes working in the office assisting the depot with Bus Driver and Fleet
Management and On Road driver operations to ensure Transdev meets its contractual obligations to Public Transport Victoria(PTV) [PTV Link](https://www.ptv.vic.gov.au/).

Applications used include Microsoft Office Suite, Transport specific software being:
Vehicle Management System (VMS) and Smartrak [ST Link](https://smartrak.com/)

Overview: This role has been a learning curve for myself in that I have acquired a
unique combination of skills to operate in the office and on the road. It's been 
a terrific journey so far, especially the challenges we have had during covid-19
to ensure the continuity of the service in highly challenginng times for the public.

Citical skills I have: 
1. Successfully Managing Drivers and Associated staff (Mechanics, Operations Contact Centre Staff) during stressful periods.
2. Effectively co-ordinating resources includig staff and fleet when absences on short notice
or a vehicle breaks down or requires a change over to a depot.
3. Learning the Office Operations quickly ad effectively to become a asset
to the team.
4. Knowledge of all the Bus Routes, so I can operate whenever there is a requiremet
(eg. sickess, annual leave) adding further flexibility to Operations.
5. From my previous experience I have continued to evolve a High Level of Customer Service, 
in particular during stressful situations where conditions and demographics can impact on service and associated risks require astute thinking, prompt action, empathy, humility 
and self control.

# Australia Post - 2005 to 2018

At Australia Post [AP Link] (https://auspost.com.au/), I worked in a variety of roles and acquired a vast knowledge of the Operation, especially in Finance where I utilized my IT skills to implement a nubmer of changes to significantly improve Customer Service through Business Process Improvement practices. 
Areas in the business I worked in include:
1. Inventory - SAP Materials Management and Plant Creation
2. Procedure and Process Mapping Implementation
3. IT - Human Resources Management and SAP for Finance
4. Finance - Credit Risk 

Critical Skills I have
1. SAP functionality including
 i)     SAP FICO for Credit Management
 ii)    SAP Materials Maintenance
 iii)   SAP ABAP and VB Scripting
 iv)    Advanced MS Excel (VB, VLOOKUP automations, linking Excel with SAP)
2. High Level Customer Service
 i)     Management had great confidence in myself to address highly problematic credit account customers
 ii)    I delivered monthly collection target results consistently after acquiring account ledgers running above delinquent collection target levels
 iii)   I successfully implemented vast learnings that I acquired to Projects and conduct Staff Training Sessions based on these learnings
 iv)    I acquired through my nominal role, project management experience, differing roles I worked in, an ability to communicate effectively across different business units and with all levels of staff from the lowest levels, through contract staff, middle and senior management.

# Memberships and Licenses

1. Australian Computer Society [ACS Link] (https://www.acs.org.au/)
2. SAP Australian Users Group [SAUG Link] (https://www.saug.com.au/home)
3. Medium Rigid License
4. Forklift Operations License